- name: Extract EOD upgrader to install directory
  unarchive:
    src: "{{ eod_installer_directory }}/{{ eod_upgrader }}"
    dest: "{{ eod_install_directory }}/"
    owner: root
    group: root

- name: Run the patch
  shell: "{{ eod_install_directory }}/bin/patch -s"
  notify:
    - restart eod
